# version: "3.8"
services:
  postgresql:
    image: postgres:15.4
    container_name: mydb
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_ROOT_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql