CREATE DATABASE tea_db;
\c tea_db

CREATE TABLE IF NOT EXISTS tea (
    tea_id serial PRIMARY KEY,
    tea_name VARCHAR (50) NOT NULL,
    tea_type VARCHAR (50) NOT NULL,
    -- temperature CHAR (4) NOT NULL,
    -- mood VARCHAR (50) NOT NULL,
    caffeinated BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS flavor (
    tea_idf INT,
    flavor VARCHAR (50),

    PRIMARY KEY (tea_idf, flavor),
    FOREIGN KEY (tea_idf)
        REFERENCES tea(tea_id)
);

CREATE TABLE IF NOT EXISTS health (
    tea_idh INT,
    benefit VARCHAR (50),

    PRIMARY KEY (tea_idh, benefit),
    FOREIGN KEY (tea_idh)
        REFERENCES tea(tea_id)
);

INSERT INTO tea (tea_name, tea_type, caffeinated)
    VALUES
        ('Jasmine', 'Green', 'yes'),
        ('English Breakfast', 'Black', 'yes'),
        ('Alishan', 'Oolong', 'yes'),
        ('Chamomile', 'Herbal', 'no'),
        ('Pepermint', 'Herbal', 'no'),
        ('Rosehip', 'Herbal', 'no'),
        ('Rooibos', 'Herbal', 'no'),
        ('Ginger', 'Herbal', 'no'),
        ('Cinnamon', 'Herbal', 'no'),
        ('Lemongrass', 'Herbal', 'no'),
        ('Tulsi', 'Herbal', 'no'),
        ('Rosemary', 'Herbal', 'no'),
        ('Olive leaf', 'Herbal', 'no'),
        ('Barley', 'Herbal', 'no'),
        ('Licorice', 'Herbal', 'no'),
        ('Eucalyptus', 'Herbal', 'no'),
        ('Iceland moss', 'Herbal', 'no'),
        ('Gingko', 'Herbal', 'no'),
        ('Ashwagandha', 'Herbal', 'no'),
        ('Sage', 'Herbal', 'no'),
        ('Raspberry leaf', 'Herbal', 'no'),
        ('Valerian root', 'Herbal', 'no'),
        ('Anise seed', 'Herbal', 'no'),
        ('ELder berry flower', 'Herbal', 'no'),
        ('Liden flower', 'Herbal', 'no'),
        ('Tumeric', 'Herbal', 'no'),
        ('Moringa', 'Herbal', 'no'),
        ('Lavender', 'Herbal', 'no'),
        ('Pine needle', 'Herbal', 'no'),
        ('Echinacea', 'Herbal', 'no'),
        ('Honeybush', 'Herbal','no'),
        ('Hibicus','Herbal','no'),
        ('Osmanthus','Herbal','no'),
        ('Chrysanthenum','Herbal','no'),
        ('Rose','Herbal','no'),
        ('Jasmine','Herbal','no'),
        ('Yarrow','Herbal','no'),
        ('Stinging nettle','Herbal','no'),
        ('Dandelion','Herbal','no'),
        ('Cranberry','Herbal','no'),
        ('St John Word','Herbal','no'),
        ('Yerba Mate','Herbal','yes'),
        ('Guava Mate','Herbal','no'),
        ('Gotu kola','Herbal','no'),
        ('Marshmallow root','Herbal','no'),
        ('Thyme','Herbal','no'),
        ('Calendula','Herbal','no'),
        ('Kuding','Herbal','no'),
        ('Jiaogulan','Herbal','no'),
        ('Passion flower','Herbal','no'),
        ('Kava','Herbal','no'),
        ('Lapacho bark','Herbal','no'),
        ('Lemon balm','Herbal','no'),
        ('Chun Mee','Green','yes'),
        ('Chun Lu','Green','yes'),
        ('Bi Luo Chun','Green','yes'),
        ('Gunpowder','Green','yes'),
        ('Maofeng','Green','yes'),
        ('Yellow','Green','yes'),
        ('Jasmine','Green','yes'),
        ('Anji Bai Cha','Green','yes'),
        ('Maojian','Green','yes'),
        ('Taping Houkui','Green','yes'),
        ('Jin Shan','Green','yes'),
        ('Lingjing (Dragon well)','Green','yes'),
        ('Sejak','Green','yes'),
        ('Ujeon','Green','yes'),
        ('Jungjak','Green','yes'),
        ('Daejak','Green','yes'),
        ('Sencha','Green','yes'),
        ('Gyokuro','Green','yes'),
        ('Kabusecha','Green','yes'),
        ('Tencha','Green','yes'),
        ('Matcha','Green','yes'),
        ('Shincha','Green','yes'),
        ('Hojicha','Green','yes'),
        ('Genmaicha','Green','yes'),
        ('Konacha','Green','yes'),
        ('Kamairicha','Green','yes'),
        ('Tamaryokucha','Green','yes'),
        ('Assam', 'Black', 'yes'),
        ('Earl Grey', 'Black', 'yes'),
        ('Darjeeling', 'Black', 'yes'),
        ('Rukeri', 'Black', 'yes'),
        ('Pu-erh', 'Black', 'yes'),
        ('Scottish Afternoon', 'Black', 'yes'),
        ('Irish Breakfast', 'Black', 'yes'),
        ('Milima', 'Black', 'yes'),
        ('Ceylon', 'Black', 'yes'),
        ('Chai', 'Black', 'yes'),
        ('Panyang Congou', 'Black', 'yes'),
        ('Keemun', 'Black', 'yes'),
        ('Lapsang Souchong', 'Black', 'yes'),
        ('Golden Tips', 'Black', 'yes'),
        ('Temi Sikkim', 'Black', 'yes'),
        ('Nimbu', 'Black', 'yes'),
        ('Wakuocha', 'Black', 'yes'),
        ('Silver Needle', 'White', 'yes'),
        ('White Peony', 'White', 'yes'),
        ('Shou Mei', 'White', 'yes'),
        ('Gong Mei', 'White', 'yes'),
        ('Darjeeling White', 'White', 'yes'),
        ('Da Hong Bao', 'Oolong', 'yes'),
        ('Shui Jin Gui', 'Oolong', 'yes'),
        ('Tie Lou Han', 'Oolong', 'yes'),
        ('Shui Xian', 'Oolong', 'yes'),
        ('Bai Jiguan', 'Oolong', 'yes'),
        ('TIeguanyin (Iron Godess)', 'Oolong', 'yes'),
        ('Mi Lan Xiang Dan Con', 'Oolong', 'yes'),
        ('Acient Tree Dan Con', 'Oolong', 'yes'),
        ('Guan Yin', 'Oolong', 'yes'),
        ('Dancong', 'Oolong', 'yes'),
        ('Cassia', 'Oolong', 'yes'),
        ('Da Yu Lin', 'Oolong', 'yes'),
        ('Dong Ding', 'Oolong', 'yes'),
        ('Dong Fang Meiren', 'Oolong', 'yes'),
        ('Pouchong', 'Oolong', 'yes'),
        ('Ruan Zhi', 'Oolong', 'yes'),
        ('Jin Xuan', 'Oolong', 'yes'),
        ('Li Shan', 'Oolong', 'yes');
        

INSERT INTO flavor (tea_idf, flavor)
    VALUES
        (1, 'Sweet'),
        (1, 'Floral');

INSERT INTO health (tea_idh, benefit)
    VALUES
        (1, 'Antioxidants'),
        (1, 'Weight Loss'),
        (1, 'Muscle Relax');